name: PaperTrails
version: 0.0.1
main: io.github.keli5.papertrails.PaperTrails
description: Dead simple particle trails for Paper
author: keli5
website: https://keli5.github.io/
api-version: 1.19

permissions:
  papertrails.preview:
      description: "Allow users to preview particle types"
      default: op
  papertrails.listparticles:
      description: "Allow users to list particle types"
      default: op
  papertrails.listmodes:
      description: "Allow users to list particle modes"
      default: op


commands:
  previewtrail:
    description: "Preview a particle effect"
    usage: "/previewtrail <particle> <mode>"
    permission: papertrails.preview

  listparticles:
    description: "See a list of allowed particle types"
    usage: "/listparticles"
    permission: papertrails.listparticles

  listmodes:
    description: "See a list of allowed particle modes"
    usage: "/listmodes"
    permission: papertrails.listmodes